# https://github.com/marketplace/actions/npm-publish

name: NPM Publish

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 14
            - name: Publish
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: '${{ secrets.NPM_TOKEN }}'